### ISSUE TITLE
Improve GitLab integration

### ISSUE THREAD

**Issue by sils1297** [gitterHQ/services#77]
There is one but it's not really helpful, especially because there are no links to anything.

Adding links to the notification messages would already help a lot I think.

**Comment by scriptnull** [comment]
I have been staring at code for solving https://github.com/gitterHQ/gitter/issues/1385 . But seems like lot of new events are available via gitlab webhooks. So, I will be sending PRs one by one for all the new webhook events and lets make gitter + gitlab , the most useful integration on the list :fire:

**Comment by scriptnull** [comment]
Here are the things in my plan.

---
### Push Event
#### Current : 
![image](https://cloud.githubusercontent.com/assets/4211715/17943810/9b8cfc24-6a5a-11e6-8f1b-9684a7bd71ae.png)

#### TODO
- [ ] Add links for username and project.
- [ ] if commit is 1 , say "pushed 1 commit" instead of "1 commits" 

---

### Tag Push Event
#### Current :
![image](https://cloud.githubusercontent.com/assets/4211715/17943539/76ce5c1c-6a59-11e6-884d-e08f14791929.png)

#### TODO
- [ ] Change message to "[user_name] pushed new tags to [project_name]" 
- [ ] Add links for username, tags page and projectname.

Sadly, gitlab doesn't provide any information about the number of tags or not even the name of the tags. May be, its wise to have a support ticket with gitlab on this.

----

### Comments ( Note events )
#### Current :
![image](https://cloud.githubusercontent.com/assets/4211715/17945037/be427794-6a5f-11e6-9699-2896adfe4872.png)

#### TODO
- [ ] Show message "[user_name] commented on #[issue_number] [issue_title] in [project_name]"
- [ ] Add links for username, comment and projectname

---

### Issue events
#### Issue open
![image](https://cloud.githubusercontent.com/assets/4211715/17944381/1b52f862-6a5d-11e6-83d4-04e44c801835.png)

#### TODO
- [ ] Make message as "[user_name] opened #[issue_number] [issue_title] in [project_name]"
- [ ] Add links for username, issue and project.

#### Issue Updates ( reopen , closed and assign etc. ) 
![image](https://cloud.githubusercontent.com/assets/4211715/17945367/2e724660-6a61-11e6-94f5-0ed13778530f.png)

#### TODO
- [ ] Make message as "[user_name] updated #[issue_number] [issue_title] \( [state] \) in [project_name]"
- [ ] Add links for username, issue and project. state will be close, open , reopen.

It would be totally good , if gitlab API gave more information on what is being updated with some kind of constants like update.ASSIGN_ISSUE, update.UNASSIGN_ISSUE etc. Will have this in mind to ask in gitlab support ticket.

----
### Merge Requests
#### Merge request create
![image](https://cloud.githubusercontent.com/assets/4211715/17945595/25af11ec-6a62-11e6-9afb-8de11ee2d9c0.png)

#### TODO
- [ ] Make message as "[user_name] created #[merge_request_number] [merge_request_title] in [project_name]"
 in [project_name]"
- [ ] Add links for username, merge request and project 

### Merge Request updates
![image](https://cloud.githubusercontent.com/assets/4211715/17946226/160c79a2-6a65-11e6-9d0c-224ed2e66151.png)

#### TODO
- [ ] Make message as "[user_name] updated #[issue_number] [issue_title] \( [state] \) in [project_name]"
- [ ] Add links for username, issue and project.

--- 

### Build Events [new]
#### TODO
-  [ ] Show messages in activity for build events.

> Design of message will be decided while sending PR.

---

### Pipeline Events [new]
#### TODO
-  [ ] Show messages in activity for pipeline events.

> Design of message will be decided while sending PR.

---

### Wiki Page events [new]
#### TODO
-  [ ] Show messages in activity for wiki page events.

> Design of message will be decided while sending PR.
